version: '3.8'

services:
  proxy:
    build: ./proxy
    ports:
      - "8080:8080"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  tester:
    build: ./proxy  # Reuse proxy image for tests
    depends_on:
      - proxy
      - backend
    command: pytest /tests
    volumes:
      - ./tests:/tests